apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aleph-ingress-dev
  namespace: dev
spec:
  rules:
    - host: aleph.devel
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: aleph-ui
                port: 
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service: 
                name: aleph-api
                port: 
                  number: 8000
