---
clusterName: "aleph-index"

replicas: 1
minimumMasterNodes: 1
clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'

image: "ghcr.io/alephdata/aleph-elasticsearch"
imageTag: "3bb5dbed97cfdb9955324d11e5c623a5c5bbc410"
imagePullPolicy: "IfNotPresent"

esJavaOpts: "-Xmx512m -Xms512m"
esConfig:
  elasticsearch.yml: |
    xpack:
      graph:
        enabled: "false"
      ml:
        enabled: "false"
      security:
        enabled: "false"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "300m"
    memory: "1G"
  limits:
    cpu: "600m"
    memory: "1G"

volumeClaimTemplate:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 6Gi

