name: Check formatting

on:
  pull_request:
    paths-ignore:
      - "ui/**"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install development dependencies
        run: make dev

      - name: Check code formatting
        run: make format-check
